- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_rsa2"
    source_pub_key: "./.ssh/id_rsa2.pub"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa2"
    pub_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa2.pub"
  tasks:
    - name: Ensure .ssh directory exists.
      file:
       dest: "{{ dest_key | dirname }}"
       mode: 0700
       owner: mint
       state: directory
    - name: Install ssh key
      copy:
       src: "{{ source_key }}"
       dest: "{{ dest_key }}"
       mode: 0600
       owner: mint
    - name: Install ssh pub key
      copy:
       src: "{{ source_pub_key }}"
       dest: "{{ pub_key }}"
       mode: 0600
       owner: mint 
    - name: Set authorized key
      authorized_key:
       user: "{{ lookup('env', 'USER') }}"
       state: present
       key: "{{ lookup('file', '~/.ssh/id_rsa2.pub') }}"
